### ISSUE TITLE
UI Design for CCstamper

### ISSUE THREAD

**Issue by TobiasWestphal** [edu-sharing/ccstamper#9]
Here are some designs for a funny new user interface. 
Animation: https://drive.google.com/open?id=0B-sb69PX_aCsX2V3VFVFcFNSa1U

![01-cc-stamper img](https://user-images.githubusercontent.com/29775863/30103256-5abaacf2-92f2-11e7-9ecb-faae903f1f66.png)
![02-cc-stamper licence](https://user-images.githubusercontent.com/29775863/30103258-5abc129a-92f2-11e7-9003-3a6bd0d8528f.png)
![03-cc-stamper author](https://user-images.githubusercontent.com/29775863/30103255-5ab9a7bc-92f2-11e7-9bd4-bf4b20e82363.png)

![05-cc-stamper stamp](https://user-images.githubusercontent.com/29775863/30103257-5abaaff4-92f2-11e7-8076-ae941b9a620a.png)

**Comment by rootzoll** [comment]
Most of the designs done.
